### ISSUE TITLE
Offline channels' stream error #1000

### ISSUE THREAD

**Issue by Bertaz** [arthurbolsoni/Purple-adblock#12]
Offline channels, that don't put last VOD or a channel trailer on the homepage, show an error.
It also happens when watching a stream and it ends, or when going to an offline channel with a video and clicking on `↗chat` so that it opens the offline stream.
Reloading or pressing the red button obviously does nothing.

Tested in an incognito window with only this extension enabled
## Offline stream full screen:
![image](https://user-images.githubusercontent.com/44445647/118916907-1bbef400-b930-11eb-93da-99e8f7b71239.png)
![image](https://user-images.githubusercontent.com/44445647/118916806-f6ca8100-b92f-11eb-8a20-0c919c2fd8ff.png)
<details>
 <summary><strong>Extension disabled</strong></summary>

![image](https://user-images.githubusercontent.com/44445647/118918626-537b6b00-b933-11eb-938d-1969e651054c.png)
</details>

## Broken video:
![image](https://user-images.githubusercontent.com/44445647/118898236-6af32d80-b90c-11eb-8b62-c4950b505b0f.png)
https://www.twitch.tv/otknetwork
<details>
 <summary><strong>Other examples:</strong></summary>

![image](https://user-images.githubusercontent.com/44445647/118900507-68df9d80-b911-11eb-8be5-0753db399365.png)
https://www.twitch.tv/moonmoon

![image](https://user-images.githubusercontent.com/44445647/118903727-a98ee500-b918-11eb-9abf-47c42ba41c10.png)
https://www.twitch.tv/montanablack88

</details>

#### Extension disabled on same channel:
![image](https://user-images.githubusercontent.com/44445647/118915595-8ae71900-b92d-11eb-9123-f3221e3d7e73.png)

<details>
 <summary><strong>Examples of offline channel with video</strong></summary>

Latest VOD:
![image](https://user-images.githubusercontent.com/44445647/118901183-ed7eeb80-b912-11eb-8469-015350b08a87.png)
https://www.twitch.tv/karlnetwork

Channel trailer:
![image](https://user-images.githubusercontent.com/44445647/118902222-87479800-b915-11eb-8991-9f860665ae73.png)
https://www.twitch.tv/gmhikaru
</details>

**Comment by arthurbolsoni** [comment]
very thanks for the report. i had do a update. i think it is fixed. but i need update the extension app too. look the update: https://github.com/arthurbolsoni/Purple-adblock/commit/4cdece325dd2c97e1f1e77033edcd0bb4bec5d9e

**Comment by dozzzz02** [comment]
@arthurbolsoni also, 

I get ads the streamer puts on when they take a break for example. All I need to do for your extension is enable it or also setup my own proxy?

**Comment by arthurbolsoni** [comment]
> @arthurbolsoni also,
> 
> I get ads the streamer puts on when they take a break for example. All I need to do for your extension is enable it or also setup my own proxy?

some users is reporting it. i see too ad on South Korea. i don't know why, i can try fix it. but i need more information. 
could you send the stream that you see the ads?
can you call me on discord https://discord.com/invite/7MpUUDNxHx
or send here https://github.com/arthurbolsoni/Purple-adblock/issues/13
