### ISSUE TITLE
ad coming

### ISSUE THREAD

**Issue by arthurbolsoni** [arthurbolsoni/Purple-adblock#13]
if you see ad, pls send you country and the stream channel for i try find a solutionm, here or discord https://discord.com/invite/7MpUUDNxHx

**Comment by dozzzz02** [comment]
Netherlands, twitch.tv/lvndmark, twitch.tv/xqcow.

I see ads on both of them, never when I enter stream. Only when I'm watching for a while a random ad comes.

**Comment by wasupman2** [comment]
United States, twitch.tv/elajjaz

Same as dozzzz02. Ads only came up while watching the stream.

**Comment by U3b3** [comment]
Getting Ads again. Germany / twitch.tv/nmplol

**Comment by Suzaru** [comment]
Yea, same. Germany https://www.twitch.tv/huskerrs

**Comment by checkraisefold** [comment]
USA, https://www.twitch.tv/xqcow rare ad when starting to watch stream

**Comment by arthurbolsoni** [comment]
can you try with adblock for see if open purple screen?

**Comment by PurpleHerby** [comment]
Sorry did notice this thread, was checking latest dates, apologise for multiple posts, my bad.

Firefox version 89 - Extension version 1.5 Date: 25 May
Chrome Version 91 - Extension version 1.5.4 Date: 14 June
Location: UK
log says "blocking success: 200"

Just go to Browse > Live Channels > Sort High to Low and start clicking.

**Comment by arthurbolsoni** [comment]
when show ads. do can you say the server bellow the "blocking success: 200"?

**Comment by PurpleHerby** [comment]
Location: UK

Chrome:
Opening: xqcow - twitch server: video-weaver.arn03.hls.ttvnw.net - Battlefield Ad
Opening: sykkuno - No server - Final Fantasy Ad
Opening: summit1g - twitch server: video-weaver.arn03.hls.ttvnw.net - Bandai Ad
Opening: sodapoppin - No Server - Safe Driving Campaign...
Opening: swagg - No Server - Hitman's Wife's Bodyguard Ad

Firefox:
Opening: xqcow - No server - Playstation GTA Ad
Opening: sodapoppin - No Server - BandaiNamco Ad
Opening: sykkuno - No Server - Xbox Scarlet Nexus
Opening: swagg - No Server - Audible
Opening: nl_kripp - No Server - Safe Driving Campaign

I only see servers reported on Chrome extension, Firefox extension is from May, Chrome June.

Other Extensions loaded: UBlock Origin, FrankerzFaceZ

Just to be clear, this is not consistant, Sometimes is only when I open the browser and it happens, other times, I can refresh and it will stop the ad and I won't see another ad if I jump between channels, sometimes it's every channel. I wish I knew how to give you more specific information. 

Ok, started checking F12 on firefox, this is the server under Network - https://video-weaver.arn03.hls.ttvnw.net

Hope that is the type of information you meant.

**Comment by arthurbolsoni** [comment]
some peoples too has reporting this. like german, uk and Netherlands. i think it is later the "call server". i updated the server now. try again some channel.

**Comment by arthurbolsoni** [comment]
the log not return 200 later "opning"?

some peoples too has reporting this. like german, uk and Netherlands. i think it is later the "call server". i updated the server now. try again some channel.

**Comment by PurpleHerby** [comment]
Just tested on both Chrome and Firefox, approximately 10 or so top channels that a few days back would always show ads if I tried. But this morning, so far. not a single advert. Nice :) 

If anything changes, shall update.

Cheers!

**Comment by arthurbolsoni** [comment]
ok, try always in 1080p pls
