### ISSUE TITLE
Ad Free Location Info For You

### ISSUE THREAD

**Issue by saucettv** [arthurbolsoni/Purple-adblock#14]
This may help for future:

Twitch has this in their settings.js file. I'm assuming, if they block prime subs in IN, they also won't be advertising there, as they can't offer ad-free streaming to subs for India users and they advertise this perk everywhere. Might be worth trying a proxy in India.

          "prime_blocked_regions": [
		"IN",
		"IND",
		"CU",
		"CUB",
		"SD",
		"SUD",
		"IR",
		"IRN",
		"CHN",
		"CN",
		"SY",
		"SYR",
		"PRK",
		"KP"
	]

	"prime_sub_blocked_regions": [
		"IN"
	]

**Comment by arthurbolsoni** [comment]
very very thanks, o gonna test a proxy IN. thanks for the list. where you find it?
