### ISSUE TITLE
Better English Desc

### ISSUE THREAD

**Issue by saucettv** [arthurbolsoni/Purple-adblock#15]
I wrote a better English description for your store page:

"Purple AdBlock is a video ad-blocker for Twitch. The extension uses an external proxy in an ad-free country, only video requests are sent through this proxy to retrieve an ad-free, full quality stream.

The extension does not collect or store your personal information and is opensource.

If you would like to contribute your own proxy or help us with the extension upkeep, please visit my Github https://github.com/arthurbolsoni

ATTENTION: Does not work with Alternate Player for Twitch.tv, Twitch ad-block userscripts or other Twitch ad-blockers.
ATTENTION: The author of this extension accepts no responsibility for the use of the extension. The use of the extension is the total responsibility of the user."

Hope this helps you :)

**Comment by saucettv** [comment]
And summary:

"Purple AdBlock is a video ad-block for Twitch."

Pretty sure you are allowed to use "for Twitch" without breaking trademarks.

**Comment by arthurbolsoni** [comment]
thanks. i edited on firefox store e waiting the google confirm the edit to chrome. i do know if i can use the name Twitch. afraid a "removed extension" from stores if i use. maybe a "Twitc" or anyone name that the sonud is the same?

**Comment by saucettv** [comment]
No problem :) Well I have https://addons.mozilla.org/en-US/firefox/addon/video-ad-block-for-twitch/ and https://chrome.google.com/webstore/detail/video-ad-block-for-twitch/kgeglempfkhalebjlogemlmeakondflc both were approved, so I think it is fine as long as you use no Twitch logo images and you use the exact words "for Twitch".
