### ISSUE TITLE
No stream anymore on twitch with extension enabled on Edge-dev for Linux.

### ISSUE THREAD

**Issue by Xarkam** [arthurbolsoni/Purple-adblock#16]
Today, 05-28-2021, this extension can't play streams.
It seems cause an HTTP Response Error: AbortError The user aborted a request.

**Comment by arthurbolsoni** [comment]
it happens on all channels or on a specific?

**Comment by Xarkam** [comment]
> it happens on all channels or on a specific?

All channels.

I tested with Vivaldi, and I don' have any problem.

I think this is specific to Edge dev which is version 92 of chromium.

**Comment by arthurbolsoni** [comment]
thanks for report. i think that could be the edge. i tried now on edge here and work. but i gonna be looking for possibles problems on edge. thanks :)

**Comment by ailailou** [comment]
Heya, issue just started happening for me with Firefox and Windows 10.
Firefox 88.0.1 (64-bit)

First noticed on https://www.twitch.tv/lirik.
Then I tried other streams and none load with the addon activated.

It worked fine last night 29th May.

**Comment by arthurbolsoni** [comment]
o gonna try on edge linux
