### ISSUE TITLE
Results in black loading screen

### ISSUE THREAD

**Issue by alkamaass** [arthurbolsoni/Purple-adblock#17]
the extension does not seem to work now, it just results in an infinite black loading screen, I have tested on both firefox and chrome

**Comment by prank855** [comment]
Same

**Comment by 1darklyte** [comment]
Also getting it. Disabling the extension and reloading the page fixes it.

**Comment by unknownids** [comment]
yea twitch implemented a fix to prevent videos from playing when using the extension.

**Comment by fREAST** [comment]
Looks like the proxy is down, trying to fetch for example https://much.ga/channel/nymn gives `524 Origin Time-out`, although https://much.ga/on returns `ok`.

**Comment by AlecJ** [comment]
Working for me now

**Comment by unknownids** [comment]
working for me now but i just got an ad using it with firefox dev edition.

**Comment by arthurbolsoni** [comment]
i updated the proxy. waiting the proxy6 power on again the old proxy.
