### ISSUE TITLE
Ads are showing again since last update

### ISSUE THREAD

**Issue by ClemGlacee** [arthurbolsoni/Purple-adblock#18]
Ads are showing again since last update to access my tabs
VPN in UK

**Comment by DannyDarth** [comment]
Same, Just got an ad

**Comment by Gundor** [comment]
same, Purple-addblock's log said : "_blocking success: 200"_ but ad coming

**Comment by PurpleHerby** [comment]
Confirming also in UK, also getting prerolls, for last couple of days. As above, states blocking success in log.

**Comment by OPSJono** [comment]
Also started seeing pre-rolls in the UK over the last few days.

**Comment by TheRayJohnson** [comment]
Getting ads also even though log says `blocking success`

![image](https://user-images.githubusercontent.com/36357206/120524341-de963f80-c3ce-11eb-90b8-551f8ad60c52.png)

**Comment by Eazor** [comment]
same for me. Also 200 but still ads are displayed

**Comment by PurpleHerby** [comment]
Firefox version 89 - Extension version 1.5  Date: 23 May
Chrome Version 91 - Extension version 1.5.4  Date: 14 June
Location: UK

Getting Ads, log says "blocking success: 200"

**Comment by ClemGlacee** [comment]
I recommend you guys to use this instead, it works perfectly
https://addons.mozilla.org/en-GB/firefox/addon/video-ad-block-for-twitch/

**Comment by PurpleHerby** [comment]
> 
> 
> I recommend you guys to use this instead, it works perfectly
> https://addons.mozilla.org/en-GB/firefox/addon/video-ad-block-for-twitch/

Thanks, I appreciate the information, I suspect a few here are already aware of the 480p solution, but I guess it doesn't hurt to share. Having said that not sure it's respectful to link another extension in an authors github without his permission. No idea on the etiquette here. 

I'll wait on a fix here if at all possible though, as 480p on a 32" monitor arguably worse than the advert. lol :)

**Comment by ClemGlacee** [comment]
> not sure it's respectful to link another extension in an authors github without his permission

We haven't had any response since 15 days now, I guess the dev either doesn't care or doesn't have time to resolve the issue




> as 480p on a 32" monitor arguably worse than the advert

You actually don't get the advert, it switches to 480p, the advert cancels and then set you back to 1080p so you are watching as you'd do with purple adblock

**Comment by PurpleHerby** [comment]
But the developer HAS been active on this project in the last few days.

> You actually don't get the advert, it switches to 480p, the advert cancels and then set you back to 1080p so you are watching as you'd do with purple adblock

I meant watching the stream at 480p was arguably worse than watching an advert, to me, at least :)

**Comment by arthurbolsoni** [comment]
i recommend the  https://addons.mozilla.org/en-GB/firefox/addon/video-ad-block-for-twitch/ too, is awesome work.

**Comment by TheRayJohnson** [comment]
> i recommend the https://addons.mozilla.org/en-GB/firefox/addon/video-ad-block-for-twitch/ too, is awesome work.

Anything for Chrome you (or others) can recommend? :(

**Comment by arthurbolsoni** [comment]
> > i recommend the https://addons.mozilla.org/en-GB/firefox/addon/video-ad-block-for-twitch/ too, is awesome work.
> 
> Anything for Chrome you (or others) can recommend? :(


Not for now. the basics only exist this method and the m3u8 proxy.
