### ISSUE TITLE
Dont seem to work now

### ISSUE THREAD

**Issue by TheMdogShow** [arthurbolsoni/Purple-adblock#19]
Just tried this and no longer seems to stop adds

**Comment by unknownids** [comment]
canada here, just got ads using it.

**Comment by innovatodev** [comment]
same here (france) since permissions update i see every single ads, world of warcraft is driving me crazy haha, i'll just keep extension enabled and hope it will works again, because everytime i see an ad in the middle of a stream just leave twitch for the day lol
