### ISSUE TITLE
Ads showing up

### ISSUE THREAD

**Issue by DannyDarth** [arthurbolsoni/Purple-adblock#27]
Just had 2 ads show up. Tried refreshing the page and still seen ads.

**Comment by arthurbolsoni** [comment]
you need restart the browser

**Comment by EthanDarling8** [comment]
I restarted the browser and it is still not working.

**Comment by arthurbolsoni** [comment]
do you can send the log ?

**Comment by DatXFire** [comment]
> do you can send the log ?

I only get pre-rolls with it currently, but no ads during playback. Here's the error that I get, they all look like this.

`blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/rinkarigani.m3u8?allow_source=true&fast_bread=true&p=1496548&play_session_id=7e3da927611edb7170fb1295bb0e7db1&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=185c1b737ab61362aaefe0bad4b788dbc7013eb4&supported_codecs=vp09%2Cavc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22rinkarigani%22%2C%22channel_id%22%3A49404569%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%22R8htBoQBQVnW4PWcZD4yeKPAnJx4o7fA%22%2C%22expires%22%3A1628225204%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22channel_home_carousel%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A37176393%2C%22user_ip%22%3A%2224.93.120.32%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.4.0`

**Comment by arthurbolsoni** [comment]
do you can send all the log?

**Comment by EthanDarling8** [comment]
Here ya go, it's only preroll ads it seems:
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/cirno_tv.m3u8?allow_source=true&fast_bread=true&p=8572366&play_session_id=28553fb2ff9b9e80a0c5fa8ff11519b1&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=d049f0a6eea2fc717c3e2447ff8b03891d72fe0a&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22cirno_tv%22%2C%22channel_id%22%3A24761645%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%22jYagzJdvRmZkoWBzfMVarwyLZ10c4HK7%22%2C%22expires%22%3A1628296826%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22site%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A243230273%2C%22user_ip%22%3A%2266.60.97.6%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.4.0

**Comment by arthurbolsoni** [comment]
yes, i not did a "auto restart" on that adblock. when the server return error by the proxy or connection problem he disable the extension. it could by anything on connection. keep eye i gonna launch a new update to fix it and more options

**Comment by arthurbolsoni** [comment]
cloudflare mistake with http/https, fixed :thumbsup:
