### ISSUE TITLE
ads again

### ISSUE THREAD

**Issue by Mencontar** [arthurbolsoni/Purple-adblock#29]
Yet again it's not blocking a single add. seems to be frequently not working....I close browser or restart PC and it's still not working. Here is my logfile, "blocking success" my ass

Opening: bolrogretro
blocking success: 200
twitch server: video-weaver.hel01.hls.ttvnw.net
Opening: iitztimmy
blocking success: 200
Opening: richwcampbell
blocking success: 200

**Comment by arthurbolsoni** [comment]
i did send  update, you can install by the github or await the store update.

**Comment by arthurbolsoni** [comment]
Closed as an exact duplicate of https://github.com/arthurbolsoni/Purple-adblock/issues/13
