### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by checkraisefold** [arthurbolsoni/Purple-adblock#30]
https://github.com/TTV-LOL/extensions/issues/22
Same issue as the other adblocking extension

**Comment by arthurbolsoni** [comment]
i am aware of this. i recommendyou try the "beta" for now.  (only chrome)
![image](https://user-images.githubusercontent.com/21229921/133357390-87667b85-41d6-4561-9d3c-48c2a0f0aa03.png)

**Comment by arthurbolsoni** [comment]
Closed as an exact duplicate of https://github.com/arthurbolsoni/Purple-adblock/issues/13
