### ISSUE TITLE
Getting pre-roll ads again

### ISSUE THREAD

**Issue by ssateneth** [arthurbolsoni/Purple-adblock#32]
Started getting pre-roll ads again on twitch.  extension ver 2.0.1, chrome ver 93.0.4577.82

**Comment by DuhMe** [comment]
I am too when using Vivaldi 4.3.2439.65 which is the latest version as of this post.

**Comment by projectshifter** [comment]
Can also confirm on Firefox 94.0 on Ubuntu 20.04.3.

**Comment by BWMerlin** [comment]
Firefox 95 on Windows 10, has only started this week for me.
