### ISSUE TITLE
Audio de-sync

### ISSUE THREAD

**Issue by CycIoneTM** [arthurbolsoni/Purple-adblock#37]
Every so often ill have to pause and play the video due to the audio being de-sync I believe this has to do with purple adblock

**Comment by Ciskow** [comment]
Yeah, same for me on Firefox 98.0.1, lots of buffering then the audio de-syncs

**Comment by arthurbolsoni** [comment]
fixed on dev branch 2.2.0 https://github.com/arthurbolsoni/Purple-adblock/tree/dev
