### ISSUE TITLE
Stream turns low quality from time to time.

### ISSUE THREAD

**Issue by RobbeSchepens** [arthurbolsoni/Purple-adblock#46]
Hi I was wondering if this is normal behavior: The streams turns to 360p every 20 minutes or so. Checking the logs of the extension, it says
[7/16/2022, 7:42:05 PM]: Initializing..
[7/16/2022, 7:42:05 PM]: Initialized

So I assume it reconnected to a different proxy or something? 
It even happens on channels I'm subbed to.

**Comment by arthurbolsoni** [comment]
you need toggle"Proxy Authentication"?
the log you can see in console of page, try press F12 in chrome, and go to console tab.
