### ISSUE TITLE
Uncaught (in promise) TypeError: this.declareEventWorker is not a function

### ISSUE THREAD

**Issue by teisseire117** [arthurbolsoni/Purple-adblock#47]
Hi,

Since previous versions were not working for me -as stated in my previous tickets, the issue was that the stream had a black screen and an infinite loading wheel icon on it-, I waited til there would be a new version.

I just noticed there's a new version, 2.2.4, so I downloaded it from the repository and loaded it in Chrome.

I still have the same issues as in previous versions, but this time I noticed there were an error message, maybe it can help sorting things out, here's a screenshot of it :
![3tlB1QP (1)](https://user-images.githubusercontent.com/43145883/180636467-e9cb508d-73c3-4d51-a0b3-567803efb799.png)

**Comment by arthurbolsoni** [comment]
i thought i did updated it

**Comment by arthurbolsoni** [comment]
https://github.com/arthurbolsoni/Purple-adblock/commit/6bc350e6774999ad060cb03f0573dcf10c478f7b

**Comment by teisseire117** [comment]
> i thought i did updated it. try now [6bc350e](https://github.com/arthurbolsoni/Purple-adblock/commit/6bc350e6774999ad060cb03f0573dcf10c478f7b)

That fixed all my problems. No more blackscreen, the ones I had since previous versions, and no more error messages, thanks !
