### ISSUE TITLE
did this break? 

### ISSUE THREAD

**Issue by EvaisaGiac** [arthurbolsoni/Purple-adblock#48]
I am getting preroll ads and regular ads while using this now

**Comment by arthurbolsoni** [comment]
looks is for all https://github.com/cleanlock/VideoAdBlockForTwitch/issues/62

**Comment by Beet4** [comment]
Can confirm that I'm getting pre-roll ads again using this extension. But not the commercial break in progress-screen that I was getting with the scripts from https://github.com/pixeltris/TwitchAdSolutions

There is an experimental userscript over there that I am trying now.
https://github.com/cleanlock/VideoAdBlockForTwitch/pull/63

**Comment by Arandomnameok** [comment]
yeah it's 101% broken they patched this a couple days ago.. getting the same garbage window fuck off twitch.

**Comment by Beet4** [comment]
I've been using

vaft - [ublock](https://github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft-ublock-origin.js) / [userscript](https://github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft.user.js) / [ublock (permalink)](https://github.com/pixeltris/TwitchAdSolutions/raw/e80025cbd1eef78f3c609eaff8d5f934abcc9cf8/vaft/vaft-ublock-origin.js)
Video Ad-Block, for Twitch (fork) as a script.
This is currently a fork of the fork, see https://github.com/cleanlock/VideoAdBlockForTwitch/pull/63.

from https://github.com/pixeltris/TwitchAdSolutions

for 2 days now, not a single ad or ad break screen so far. Working pretty good from what I can tell!

**Comment by arthurbolsoni** [comment]
recommend try the last script. now work with tampermonkey too https://github.com/arthurbolsoni/Purple-adblock/blob/main/tampermonkey/dist/purpleadblocker.user.js

**Comment by pixeltris** [comment]
Hi @arthurbolsoni. Could you give an overview of what your extension does now? I see you're using the embed player. You're also contacting your `jupter.ga` proxy, but I don't think that is doing anything useful?

**Comment by arthurbolsoni** [comment]
since I started writing the script in typescript I put the request proxy option (because the extension started like this, and there is also a server already built).

the idea is simple. the script first tries the first strategy (embed), then 480p (doesn't work anymore) and lastly the proxy. if the proxy is disabled it is just not used.

the latest version the proxy is always enabled. because I thought I could show ads again and many people don't know they have this option

**Comment by arthurbolsoni** [comment]
the m3u8 are always called in start because the time response is 3sec and the player can not wait 3 sec em mid-rolls

**Comment by HashBR** [comment]
Is the plugin working now? If so, can you update for FF as well, please? Thank you.
