### ISSUE TITLE
Stream randomly goes offline 

### ISSUE THREAD

**Issue by ADRBT** [arthurbolsoni/Purple-adblock#49]
For some reason, while using the extension whatever stream I'm watching just goes offline after a random amount of time. Even after page reload and browser restart.
(Using Opera GX)

**Comment by Libror** [comment]
Having the same problem. It buffers for a long amount of time and then just goes offline.

**Comment by arthurbolsoni** [comment]
https://github.com/arthurbolsoni/Purple-adblock/releases/tag/2.5.1
