### ISSUE TITLE
Ads comes through

### ISSUE THREAD

**Issue by revunix** [arthurbolsoni/Purple-adblock#5]
Something is not right here. Please check your proxy.

**Comment by arthurbolsoni** [comment]
can you see if m3u8 is returning (USER-COUNTRY="RU") ? you can see in F12 > Network, navegate to channel twitch, and search for the much.ga/channel/...

**Comment by revunix** [comment]
> (USER-COUNTRY="RU")
Yes, its back. I try it now a few hours and give a feedback later 🤓

**Comment by revunix** [comment]
works well so far 🥳

**Comment by arthurbolsoni** [comment]
do you are using firefox version?

**Comment by revunix** [comment]
no i'm using chrome version on brave.

**Comment by arthurbolsoni** [comment]
i will let this thread open, if anyone have something to append

**Comment by amethystau** [comment]
streams not loading at all on firefox right now

**Comment by arthurbolsoni** [comment]
> streams not loading at all on firefox right now

you are using the store version? ou the github

**Comment by arthurbolsoni** [comment]
> streams not loading at all on firefox right now

try in (private mode) and look if run only with the "Purple extension".
try access https://much.ga/on and look if return "ok" if have a error maybe you connection.

**Comment by amethystau** [comment]
it's working again now. when it was broken earlier i tried both store version and github version.
