### ISSUE TITLE
not blocking ads as of 29/09

### ISSUE THREAD

**Issue by samargy** [arthurbolsoni/Purple-adblock#50]
Log is as follows

Opening: toastracktv
server off
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/kimandjax.m3u8?allow_source=true&fast_bread=true&p=1667612&play_session_id=5440c689ddf76f9dc4b92f5173b1c326&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=85ae5a7d16c51cbe5909b591bdaf35dbde06653e&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22kimandjax%22%2C%22channel_id%22%3A159385099%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%228i1taOrNhTwxCOFdzTLbaTQUlAmYJQmD%22%2C%22expires%22%3A1664408994%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22frontpage%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A61774899%2C%22user_ip%22%3A%22119.18.1.44%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.14.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/hasanabi.m3u8?allow_source=true&fast_bread=true&p=1053379&play_session_id=9ea22faed6bf3eab74428ffd66b71dad&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=c6892e587a4325ce006d129f7dcc9ad2dd71ea2c&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22hasanabi%22%2C%22channel_id%22%3A207813352%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%228i1taOrNhTwxCOFdzTLbaTQUlAmYJQmD%22%2C%22expires%22%3A1664409002%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22site%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A61774899%2C%22user_ip%22%3A%22119.18.1.44%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.14.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/hasanabi.m3u8?allow_source=true&fast_bread=true&p=932315&play_session_id=272999180307ac3d2eba6d0de92408c8&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=b2e29d3e3900e23bbff8b3f839e7e3c67cda888c&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22hasanabi%22%2C%22channel_id%22%3A207813352%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%228i1taOrNhTwxCOFdzTLbaTQUlAmYJQmD%22%2C%22expires%22%3A1664409008%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22site%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A61774899%2C%22user_ip%22%3A%22119.18.1.44%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.14.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/kimandjax.m3u8?allow_source=true&fast_bread=true&p=5120152&play_session_id=a3355b559dbe8983ec4bd99b2e5b7dbb&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=5b127da16ee6db9c105381824bb6d5caa50b6b56&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22kimandjax%22%2C%22channel_id%22%3A159385099%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%228i1taOrNhTwxCOFdzTLbaTQUlAmYJQmD%22%2C%22expires%22%3A1664413016%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22frontpage%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A61774899%2C%22user_ip%22%3A%22119.18.1.44%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.14.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/kaicenat.m3u8?allow_source=true&fast_bread=true&p=4999068&play_session_id=49498f71bb4885f777a31fa8585e802d&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=b287d1157a885e9d69bb3a9d587c2eeaa4243cbf&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22kaicenat%22%2C%22channel_id%22%3A641972806%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%228i1taOrNhTwxCOFdzTLbaTQUlAmYJQmD%22%2C%22expires%22%3A1664413017%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22site%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A61774899%2C%22user_ip%22%3A%22119.18.1.44%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.14.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/kaicenat.m3u8?allow_source=true&fast_bread=true&p=7193531&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=03de1d346ab954b219a60b7234830396a490feb3&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22kaicenat%22%2C%22channel_id%22%3A641972806%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%228i1taOrNhTwxCOFdzTLbaTQUlAmYJQmD%22%2C%22expires%22%3A1664414011%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Atrue%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22picture-by-picture%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Afalse%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A61774899%2C%22user_ip%22%3A%22119.18.1.44%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.14.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/reapz.m3u8?allow_source=true&fast_bread=true&p=2969697&play_session_id=385c0814560b27654b9e54bc58192c31&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=cb5875fa8489b67bb607062fcfcc395443c28fbb&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22reapz%22%2C%22channel_id%22%3A59302411%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%228i1taOrNhTwxCOFdzTLbaTQUlAmYJQmD%22%2C%22expires%22%3A1664415483%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22frontpage%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A61774899%2C%22user_ip%22%3A%22119.18.1.44%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.14.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/kaicenat.m3u8?allow_source=true&fast_bread=true&p=2999068&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=4b1c70921f60c3461bec5ad073e08fa7c17bd274&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22kaicenat%22%2C%22channel_id%22%3A641972806%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%228i1taOrNhTwxCOFdzTLbaTQUlAmYJQmD%22%2C%22expires%22%3A1664415753%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Atrue%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22picture-by-picture%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Afalse%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A61774899%2C%22user_ip%22%3A%22119.18.1.44%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.14.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/kingkitten.m3u8?allow_source=true&fast_bread=true&p=7347182&play_session_id=75a7ebec22ade1b5452f312e2d0b1d55&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=3e23220488978368d1eb22afae0de1e3f77a9eda&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22kingkitten%22%2C%22channel_id%22%3A54101395%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%228i1taOrNhTwxCOFdzTLbaTQUlAmYJQmD%22%2C%22expires%22%3A1664416531%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22frontpage%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A61774899%2C%22user_ip%22%3A%22119.18.1.44%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.14.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/caedrel.m3u8?allow_source=true&fast_bread=true&p=7301939&play_session_id=a741b991d2451bea20cd7eb7f332e938&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=c0caaa39bf717cac81c8161c5abe0cb7a802cb53&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22caedrel%22%2C%22channel_id%22%3A92038375%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%228i1taOrNhTwxCOFdzTLbaTQUlAmYJQmD%22%2C%22expires%22%3A1664416534%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22site%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A61774899%2C%22user_ip%22%3A%22119.18.1.44%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.14.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/toastracktv.m3u8?allow_source=true&fast_bread=true&p=5096936&play_session_id=a2268026aba0d845488c10d0c74edc1f&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=2265f62c4f426ee5c4459e0f2cfbde5e5e7cdf6d&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22toastracktv%22%2C%22channel_id%22%3A69439030%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%228i1taOrNhTwxCOFdzTLbaTQUlAmYJQmD%22%2C%22expires%22%3A1664419575%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22frontpage%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A61774899%2C%22user_ip%22%3A%2213.238.41.25%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.14.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/kaicenat.m3u8?allow_source=true&fast_bread=true&p=2458057&play_session_id=cac780265e461e462c717c7f3687c612&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=270d1731195d267c26bd75f5c5a9bb2d93841f27&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22kaicenat%22%2C%22channel_id%22%3A641972806%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%228i1taOrNhTwxCOFdzTLbaTQUlAmYJQmD%22%2C%22expires%22%3A1664419579%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22site%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A61774899%2C%22user_ip%22%3A%2213.238.41.25%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.14.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/esl_australia.m3u8?allow_source=true&fast_bread=true&p=9045216&play_session_id=141ae0fe972b3781c7d34aef99ca5879&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=155e07faa5ca49bd607e5aff628eea90fb060a5d&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22esl_australia%22%2C%22channel_id%22%3A31058366%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%228i1taOrNhTwxCOFdzTLbaTQUlAmYJQmD%22%2C%22expires%22%3A1664439696%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22frontpage%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A61774899%2C%22user_ip%22%3A%22119.18.1.44%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.14.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/xqc.m3u8?allow_source=true&fast_bread=true&p=5595928&play_session_id=62d3b2ca6d19f6620ccce65cd40f2ef0&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=564eaf49a93ff854734a7f016a04ebf4c431ae21&supported_codecs=avc1&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22xqc%22%2C%22channel_id%22%3A71092938%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%228i1taOrNhTwxCOFdzTLbaTQUlAmYJQmD%22%2C%22expires%22%3A1664439703%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22site%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A61774899%2C%22user_ip%22%3A%22119.18.1.44%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.14.0
blocking error: running nativeurl: https://usher.ttvnw.net/api/channel/hls/xqc.m3u8?allow_source=true&fast_bread=true&p=8909478&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=78ac1c3a127603255beb2f82b71ba5b2fc789079&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22xqc%22%2C%22channel_id%22%3A71092938%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3A%228i1taOrNhTwxCOFdzTLbaTQUlAmYJQmD%22%2C%22expires%22%3A1664440292%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Atrue%2C%22https_required%22%3Atrue%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3A%22web%22%2C%22player_type%22%3A%22picture-by-picture%22%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22role%22%3A%22%22%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Afalse%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3A61774899%2C%22user_ip%22%3A%22119.18.1.44%22%2C%22version%22%3A2%7D&cdm=wv&player_version=1.14.0

**Comment by arthurbolsoni** [comment]
server for firefox is back
