### ISSUE TITLE
How to install new release in Vivaldi

### ISSUE THREAD

**Issue by formtapez** [arthurbolsoni/Purple-adblock#54]
Hello,
i would like to install a newer version from the releases-tab in my Vivaldi Browser (chrome based).
Is it safe to just overwrite the files from the webstore i found in
`c:\Users\***\AppData\Local\Vivaldi\User Data\Default\Extensions\lkgcfobnmghhbhgekffaadadhmeoindg\2.4.1_0\`
or is there another way?

**Comment by arthurbolsoni** [comment]
Não tenho informações sobre o navegador vivaldi. pode ser algum tipo de incopatibilidade com extensoes do tipo. recomendo tentar utilizando o script pelo Tampermonkey. Voce pode o script no https://github.com/arthurbolsoni/Purple-adblock/blob/main/README.md
