### ISSUE TITLE
Extension does not work whatsoever. Tampermonkey script does work however causes large amounts of buffering and stream stuttering

### ISSUE THREAD

**Issue by daaanker** [arthurbolsoni/Purple-adblock#55]
using firefox btw

**Comment by thinkpad4** [comment]
FOr me neither the extension or the script work anymore on Chrome or Firefox

**Comment by CycIoneTM** [comment]
Works fine for me on edge

**Comment by TsukiZero** [comment]
Super stuttery and buffery on Firefox. Also, the script is a single-line-mess.
