### ISSUE TITLE
Unable to download for Firefox

### ISSUE THREAD

**Issue by Monkeymanfire** [arthurbolsoni/Purple-adblock#56]
![image](https://user-images.githubusercontent.com/65058980/202975098-1142d7f2-5d5e-4d05-b3ba-5f1a50ce904a.png)

After attempting to update manually got this error. Using Firefox Version 107.0 (64-bit)

**Comment by arthurbolsoni** [comment]
Firefox does not allow you to permanently install unsigned extensions, that is, the firefox versions on github are for testing purposes only. I recommend using the script through tampermonkey, that way it's simple and gets updates automatically.
