### ISSUE TITLE
Getting pre-roll ads on Twitch

### ISSUE THREAD

**Issue by 32423d** [arthurbolsoni/Purple-adblock#59]
I am on the latest version of the extension and I am getting pre-roll ads on Twitch. This issue started occurring today. The same channels with pre-roll ads today didn't have pre-roll ads yesterday so I am not sure if this is an issue that randomly occurs or if it will be reoccurring in the future.

**Comment by Suprcheese** [comment]
I've also noticed this happen starting today.

**Comment by arthurbolsoni** [comment]
this will happen sometimes. this happens because while the script is loading, a stream loads first. but after 1-2sec the ad is blocked

**Comment by arthurbolsoni** [comment]
https://github.com/arthurbolsoni/Purple-adblock/issues/60#issuecomment-1416808161

**Comment by Bun01294** [comment]
I'm getting prerolls but if i reset the player its permanently gone, i also get buffering issues and have to reset, but a few mins they're all gone

**Comment by eldepor** [comment]
I'm having ads with 2.5.1. So I switched back to 2.5.0.9 and it's working perfectly.

**Comment by Bun01294** [comment]
i'll try that and see what happens.

**Comment by Bun01294** [comment]
> I'm having ads with 2.5.1 tempermonkey script. So I switched back to 2.5.0.9 and it's working perfectly.

Are you using chrome, i can't get to work in firefox. and i think the unsigned xpi only works in the developer edition

**Comment by eldepor** [comment]
> > I'm having ads with 2.5.1 tempermonkey script. So I switched back to 2.5.0.9 and it's working perfectly.
> 
> Are you using chrome? i can't get to work in firefox. and i think the unsigned xpi only works in the developer edition

Yes. But I'm using the script version with tampermonkey, not the extension version.

**Comment by Bun01294** [comment]
Cool, installed it then, and see if i don't run into any issues

**Comment by Bun01294** [comment]
It was working but got infinite black loading screen and buffers, feels like twitch is watching us. I'm going to bed i'll do this later in the afternoon

**Comment by eldepor** [comment]
That's weird man, I ain't getting any issues, works beautifully. Have you disabled any other twitch ad block, script, etc and use just the one from the link in Tampermonkey?

**Comment by Bun01294** [comment]
> That's weird man, I ain't getting any issues, works beautifully. Have you disabled any other twitch ad block, script, etc and use just the one from the link in Tampermonkey?

I disabled all other extensions in firefox and i still have buffer issues, black screen and somehow an ad would appear.
I tried to test it on chrome byself and same issue sadly. 
The newer version work but the crappy pre-roll would leak but only once when and every time i hop into a different streamer.

**Comment by Bun01294** [comment]
It just the pre-roll issue that i have with the 2.5.1/2.5.3 that i only, everything else works perfectly

**Comment by eldepor** [comment]
Pls try this one, I put the wrong link before

https://github.com/arthurbolsoni/Purple-adblock/raw/63cbfa3d31778123df2eb6b017bf948a05f69421/tampermonkey/dist/purpleadblocker.user.js

**Comment by Bun01294** [comment]
Its still the same one,  i still same issues. You using any other scripts/setups? Could be that twitch is using different settings for different users

**Comment by eldepor** [comment]
> Its still the same one, i still have the same issues. You using any other scripts/setups? I thinik that twitch is using different settings for different users. With the 2.5.0.9 you gave i only get to the infinite black screen

:(
Nope, just a fresh install of Firefox on W7. I remember I had that infinite black screen issues with other tw. adbl. extensions and scripts. So I deleted all of them and installed just this script, which what works better for me. :S

**Comment by arthurbolsoni** [comment]
> Are you using chrome? i can't get to work in firefox. and i think the unsigned xpi only works in the developer edition

do the following:
disable all your browser extensions (leave only the tampermonkey script);
go to a stream where the problem occurs;
press "F12" go to the "console" tab;
there will be many logs. copy or take a print where you can see everything. and send it here or on discord. so I can know where the script is giving error to be able to solve it

**Comment by Bun01294** [comment]
[buffer and infinite black loading screen.zip](https://github.com/arthurbolsoni/Purple-adblock/files/10691999/buffer.and.infinite.black.loading.screen.zip)
 One for the crazy buffer it does, the stream starts to lag and the other one is the loading screen issue. I'm using 2.5.0.9

**Comment by arthurbolsoni** [comment]
https://github.com/arthurbolsoni/Purple-adblock/issues/79
