### ISSUE TITLE
getting pre rolls ads and middle ads

### ISSUE THREAD

**Issue by haguinaros** [arthurbolsoni/Purple-adblock#62]
the expansion works fine with me intil this day, i hope that this issue will be solve. thank for your work.

**Comment by tekinomikata** [comment]
its ultra broken now getting all kind of ads. unhappily I wonder if they can even fix these changes

**Comment by guilherme661** [comment]
parou de funcionar

**Comment by tekinomikata** [comment]
guess it was nice while it lasted... sadge

**Comment by arthurbolsoni** [comment]
https://github.com/arthurbolsoni/Purple-adblock/issues/79
