### ISSUE TITLE
No Video output just loading screen

### ISSUE THREAD

**Issue by LivePlayerHD** [arthurbolsoni/Purple-adblock#63]
I use Purple adblock with tampermonkey and i get only a loading screen when i use it.
When i disable purple adblock than the stream work.
<img width="1259" alt="Bildschirm­foto 2023-03-09 um 10 39 18" src="https://user-images.githubusercontent.com/74984092/223984421-e879fbe2-a317-4e13-a0cb-76c4034610d8.png">

**Comment by K3LS0** [comment]
Experiencing the same thing.

**Comment by mitchweaver** [comment]
same issue, its broken right now

**Comment by panicthescaredycat** [comment]
Yea.. Same here, tried to downgrade but didn't help unfortunately.. Guess all we can do is wait............. or also donate in hopes that it'll be a way of appreciating the creator's work and hoping for a fix soon? idk lol

**Comment by ElHave247** [comment]
Im my experience i had this when was working, and was just because dont skip the publicity just dont show, and when the publicity ends the stream continues playing, but a trick is just press F5 and you play directly stream again.

**Comment by arthurbolsoni** [comment]
I uploaded a current branch "dev" for chrome and firefox

**Comment by arthurbolsoni** [comment]
https://github.com/arthurbolsoni/Purple-adblock/issues/79
