### ISSUE TITLE
Still showing ads

### ISSUE THREAD

**Issue by Aolzarin** [arthurbolsoni/Purple-adblock#64]
today i added the extension to chrome but the ads are still showing... Vodafone freezone shows lots of ads :)))

**Comment by ElHave247** [comment]
Yeah is not working properly from months ago.

**Comment by arthurbolsoni** [comment]
I uploaded a current branch "dev" for chrome and firefox. try it https://github.com/arthurbolsoni/Purple-adblock/releases/tag/2.5.5

**Comment by Aolzarin** [comment]
> I uploaded a current branch "dev" for chrome and firefox. try it https://github.com/arthurbolsoni/Purple-adblock/releases/tag/2.5.5

I downloaded 2 files here, xpi and zip files, how do I add chrome? I don't know.

**Comment by Aolzarin** [comment]
ohh okey i did it.

**Comment by Aolzarin** [comment]
> I uploaded a current branch "dev" for chrome and firefox. try it https://github.com/arthurbolsoni/Purple-adblock/releases/tag/2.5.5

Is there any problem if I use another adblock besides this program?

**Comment by arthurbolsoni** [comment]
t doesn't work with "Alternate Player for Twitch.tv", or other "twitch adblockers", but you can use generic ad blockers like "uBlock Origin".

**Comment by CurlySparkle** [comment]
I've tested the new version and compare it with the previous one that was mentioned before that still seems to work fine today which is the 2.5.0.9, and so far most of the times the new one works while other times seems that ads still seems to randomly appear sadly.

**Comment by ElHave247** [comment]
> I uploaded a current branch "dev" for chrome and firefox. try it https://github.com/arthurbolsoni/Purple-adblock/releases/tag/2.5.5

Now is working perfect thanks, i can tell i have like other 20 extentions one of then is adblock and doesnt have any problems.

**Comment by ElHave247** [comment]
> > I uploaded a current branch "dev" for chrome and firefox. try it https://github.com/arthurbolsoni/Purple-adblock/releases/tag/2.5.5
> 
> I downloaded 2 files here, xpi and zip files, how do I add chrome? I don't know.

Dowload zip extract somewhere, and in chrome/brave/chronium browsers go to mange extensions and clic install packaged extension

**Comment by Aolzarin** [comment]
I want to give updated information; THIS AD BLOCKER IS AMAZING DUDE !!! THANKS ! It's like I'm subscribed to all channels no ads!!

**Comment by arthurbolsoni** [comment]
https://github.com/arthurbolsoni/Purple-adblock/issues/79
