### ISSUE TITLE
Project is abandoned?

### ISSUE THREAD

**Issue by ElHave247** [arthurbolsoni/Purple-adblock#65]
Is not working since some months, and there are no answers in the others opened issues, so we can still understand this is not going to get supported anymore?

**Comment by arthurbolsoni** [comment]
Apologies for the delay between updates I've been using all my time for my updated work. but I have updates released on the dev branch: https://github.com/arthurbolsoni/Purple-adblock/tree/develop

If anyone finds a better way to bypass adsense I'm happy to accept pull requests

**Comment by arthurbolsoni** [comment]
I uploaded a current branch "dev" for chrome and firefox
