### ISSUE TITLE
User Script link not work

### ISSUE THREAD

**Issue by gabri25ele** [arthurbolsoni/Purple-adblock#68]
please correct User Script link.

**Comment by arthurbolsoni** [comment]
Fixed link in readme.md

**Comment by gabri25ele** [comment]
so is that, right?
// @updateURL    https://raw.githubusercontent.com/arthurbolsoni/Purple-adblock/main/tampermonkey/dist/purpleadblocker.user.js

**Comment by gabri25ele** [comment]
anyway still give me error on update
![sshot-1](https://github.com/arthurbolsoni/Purple-adblock/assets/33927879/470b661f-ceb9-4418-b88b-b5e9fb0fe878)
