### ISSUE TITLE
No ads, but a little bit of delay

### ISSUE THREAD

**Issue by CharisardTT** [arthurbolsoni/Purple-adblock#71]
I'm testing the extension and it works perfectly, but i have a few seconds of delay with it. Is it possible to fix it?

**Comment by ralph409409** [comment]
Run with Tampermonkey script would keep video reading in black, should it still need open to run?

**Comment by CharisardTT** [comment]
@EldritchEevee can't you change the delay in some way?

**Comment by arthurbolsoni** [comment]
https://github.com/arthurbolsoni/Purple-adblock/issues/79
