### ISSUE TITLE
Missing: The ENTIRETY of channel info, including Stream info

### ISSUE THREAD

**Issue by TsukiZero** [arthurbolsoni/Purple-adblock#93]
![image](https://github.com/arthurbolsoni/Purple-adblock/assets/78157224/a94a71a3-38bc-423f-8872-d0929d11747d)
This really shouldn't happen. Look at that huge blank down there.

Also simply disabling PAB in the channel does nothing, only removing the ENTIRETY of PAB fixes it.

**Comment by somebirby** [comment]
Same issue and "fix" here:
Can watch ongoing streams, but the rest of the website is non-functional.
Only disabling the addon resolves it.

**Comment by IniTW8X** [comment]
Same issue here, in Brave browser.
Disabling the addon fixed the issue with most of the Twitch functionality in "error" state.

**Comment by arthurbolsoni** [comment]
https://github.com/arthurbolsoni/Purple-adblock/issues/94
